name: "自动更新LOOP/plugin/GitHub.plugin文件"

on:
  schedule:
    # 每隔60分钟运行一次
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 授予对仓库内容的写入权限

    steps:
      - name: "导入仓库"
        uses: actions/checkout@v3

      - name: "安装python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: "安装项目依赖"
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: "运行脚本"
        run: python scripts/update_GitHubHost.py

      - name: "刷新索引"
        run: git update-index -q --refresh

      - name: "配置Git"
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes 和 commit
        run: |
          if [ "$(git status --porcelain)" ]; then 
            git add LOOP/plugin/GitHub.plugin
            git commit -m "Auto-update by script"
            git push origin main
          else 
            echo "No changes to commit"
          fi
